.TH nominatim "1" Manual
.SH NAME
nominatim
.SH SYNOPSIS
.B nominatim
[-h] {import,freeze,replication,special-phrases,add-data,index,refresh,admin,export,serve,search,reverse,lookup,details,status} ...
.SH DESCRIPTION
    Command\-line tools for importing, updating, administrating and
.br
    querying the Nominatim database.
.br
    
.SH OPTIONS


.SS
\fBSub-commands\fR
.TP
\fBnominatim\fR \fI\,import\/\fR
    Create a new Nominatim database from an OSM file.
.TP
\fBnominatim\fR \fI\,freeze\/\fR
    Make database read-only.
.TP
\fBnominatim\fR \fI\,replication\/\fR
    Update the database using an online replication service.
.TP
\fBnominatim\fR \fI\,special-phrases\/\fR
    Import special phrases.
.TP
\fBnominatim\fR \fI\,add-data\/\fR
    Add additional data from a file or an online source.
.TP
\fBnominatim\fR \fI\,index\/\fR
    Reindex all new and modified data.
.TP
\fBnominatim\fR \fI\,refresh\/\fR
    Recompute auxiliary data used by the indexing process.
.TP
\fBnominatim\fR \fI\,admin\/\fR
    Analyse and maintain the database.
.TP
\fBnominatim\fR \fI\,export\/\fR
    Export addresses as CSV file from the database.
.TP
\fBnominatim\fR \fI\,serve\/\fR
    Start a simple web server for serving the API.
.TP
\fBnominatim\fR \fI\,search\/\fR
    Execute a search query.
.TP
\fBnominatim\fR \fI\,reverse\/\fR
    Execute API reverse query.
.TP
\fBnominatim\fR \fI\,lookup\/\fR
    Execute API lookup query.
.TP
\fBnominatim\fR \fI\,details\/\fR
    Execute API details query.
.TP
\fBnominatim\fR \fI\,status\/\fR
    Execute API status query.
.SH OPTIONS 'nominatim import'
usage: nominatim import [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                        (--osm-file FILE | --continue {load-data,indexing,db-postprocess})
                        [--osm2pgsql-cache SIZE] [--reverse-only]
                        [--no-partitions] [--no-updates] [--ignore-errors]
                        [--index-noanalyse]

    Create a new Nominatim database from an OSM file.
.br

.br
    This sub\-command sets up a new Nominatim database from scratch starting
.br
    with creating a new database in Postgresql. The user running this command
.br
    needs superuser rights on the database.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-osm\-file\fR FILE
OSM file to be imported (repeat for importing multiple files)

.TP
\fB\-\-continue\fR {load\-data,indexing,db\-postprocess}
Continue an import that was interrupted

.TP
\fB\-\-osm2pgsql\-cache\fR SIZE
Size of cache to be used by osm2pgsql (in MB)

.TP
\fB\-\-reverse\-only\fR
Do not create tables and indexes for searching

.TP
\fB\-\-no\-partitions\fR
Do not partition search indices (speeds up import of single country extracts)

.TP
\fB\-\-no\-updates\fR
Do not keep tables that are only needed for updating the database later

.TP
\fB\-\-ignore\-errors\fR
Continue import even when errors in SQL are present

.TP
\fB\-\-index\-noanalyse\fR
Do not perform analyse operations during index (expert only)

.SH OPTIONS 'nominatim freeze'
usage: nominatim freeze [-h] [-q] [-v] [--project-dir DIR] [-j NUM]

    Make database read\-only.
.br

.br
    About half of data in the Nominatim database is kept only to be able to
.br
    keep the data up\-to\-date with new changes made in OpenStreetMap. This
.br
    command drops all this data and only keeps the part needed for geocoding
.br
    itself.
.br

.br
    This command has the same effect as the `\-\-no\-updates` option for imports.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.SH OPTIONS 'nominatim replication'
usage: nominatim replication [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                             [--init] [--no-update-functions]
                             [--check-for-updates] [--once] [--no-index]
                             [--osm2pgsql-cache SIZE]
                             [--socket-timeout SOCKET_TIMEOUT]

    Update the database using an online replication service.
.br

.br
    An OSM replication service is an online service that provides regular
.br
    updates (OSM diff files) for the planet or update they provide. The OSMF
.br
    provides the primary replication service for the full planet at
.br
    https://planet.osm.org/replication/ but there are other providers of
.br
    extracts of OSM data who provide such a service as well.
.br

.br
    This sub\-command allows to set up such a replication service and download
.br
    and import updates at regular intervals. You need to call '\-\-init' once to
.br
    set up the process or whenever you change the replication configuration
.br
    parameters. Without any arguments, the sub\-command will go into a loop and
.br
    continuously apply updates as they become available. Giving `\-\-once` just
.br
    downloads and imports the next batch of updates.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-init\fR
Initialise the update process

.TP
\fB\-\-no\-update\-functions\fR
Do not update the trigger function to support differential updates.

.TP
\fB\-\-check\-for\-updates\fR
Check if new updates are available and exit

.TP
\fB\-\-once\fR
Download and apply updates only once. When not set, updates are continuously applied

.TP
\fB\-\-no\-index\fR
Do not index the new data. Only usable together with \-\-once

.TP
\fB\-\-osm2pgsql\-cache\fR SIZE
Size of cache to be used by osm2pgsql (in MB)

.TP
\fB\-\-socket\-timeout\fR \fI\,SOCKET_TIMEOUT\/\fR
Set timeout for file downloads

.SH OPTIONS 'nominatim special-phrases'
usage: nominatim special-phrases [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                                 [--import-from-wiki] [--import-from-csv FILE]
                                 [--no-replace]

    Import special phrases.
.br

.br
    Special phrases are search terms that narrow down the type of object
.br
    that should be searched. For example, you might want to search for
.br
    'Hotels in Barcelona'. The OSM wiki has a selection of special phrases
.br
    in many languages, which can be imported with this command.
.br

.br
    You can also provide your own phrases in a CSV file. The file needs to have
.br
    the following five columns:
.br
     * phrase \- the term expected for searching
.br
     * class \- the OSM tag key of the object type
.br
     * type \- the OSM tag value of the object type
.br
     * operator \- the kind of search to be done (one of: in, near, name, \-)
.br
     * plural \- whether the term is a plural or not (Y/N)
.br

.br
    An example file can be found in the Nominatim sources at
.br
    'test/testdb/full_en_phrases_test.csv'.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-import\-from\-wiki\fR
Import special phrases from the OSM wiki to the database

.TP
\fB\-\-import\-from\-csv\fR FILE
Import special phrases from a CSV file

.TP
\fB\-\-no\-replace\fR
Keep the old phrases and only add the new ones

.SH OPTIONS 'nominatim add-data'
usage: nominatim add-data [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                          (--file FILE | --diff FILE | --node ID | --way ID | --relation ID | --tiger-data DIR)
                          [--use-main-api] [--osm2pgsql-cache SIZE]
                          [--socket-timeout SOCKET_TIMEOUT]

    Add additional data from a file or an online source.
.br

.br
    This command allows to add or update the search data in the database.
.br
    The data can come either from an OSM file or single OSM objects can
.br
    directly be downloaded from the OSM API. This function only loads the
.br
    data into the database. Afterwards it still needs to be integrated
.br
    in the search index. Use the `nominatim index` command for that.
.br

.br
    The command can also be used to add external non\-OSM data to the
.br
    database. At the moment the only supported format is TIGER housenumber
.br
    data. See the online documentation at
.br
    https://nominatim.org/release\-docs/latest/admin/Import/#installing\-tiger\-housenumber\-data\-for\-the\-us
.br
    for more information.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-file\fR FILE
Import data from an OSM file or diff file

.TP
\fB\-\-diff\fR FILE
Import data from an OSM diff file (deprecated: use \-\-file)

.TP
\fB\-\-node\fR ID
Import a single node from the API

.TP
\fB\-\-way\fR ID
Import a single way from the API

.TP
\fB\-\-relation\fR ID
Import a single relation from the API

.TP
\fB\-\-tiger\-data\fR DIR
Add housenumbers from the US TIGER census database

.TP
\fB\-\-use\-main\-api\fR
Use OSM API instead of Overpass to download objects

.TP
\fB\-\-osm2pgsql\-cache\fR SIZE
Size of cache to be used by osm2pgsql (in MB)

.TP
\fB\-\-socket\-timeout\fR \fI\,SOCKET_TIMEOUT\/\fR
Set timeout for file downloads

.SH OPTIONS 'nominatim index'
usage: nominatim index [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                       [--boundaries-only] [--no-boundaries] [--minrank RANK]
                       [--maxrank RANK]

    Reindex all new and modified data.
.br

.br
    Indexing is the process of computing the address and search terms for
.br
    the places in the database. Every time data is added or changed, indexing
.br
    needs to be run. Imports and replication updates automatically take care
.br
    of indexing. For other cases, this function allows to run indexing manually.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-boundaries\-only\fR
Index only administrative boundaries.

.TP
\fB\-\-no\-boundaries\fR
Index everything except administrative boundaries.

.TP
\fB\-\-minrank\fR RANK, \fB\-r\fR RANK
Minimum/starting rank

.TP
\fB\-\-maxrank\fR RANK, \fB\-R\fR RANK
Maximum/finishing rank

.SH OPTIONS 'nominatim refresh'
usage: nominatim refresh [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                         [--postcodes] [--word-counts] [--address-levels]
                         [--functions] [--wiki-data] [--importance]
                         [--website] [--no-diff-updates]
                         [--enable-debug-statements]

    Recompute auxiliary data used by the indexing process.
.br

.br
    This sub\-commands updates various static data and functions in the database.
.br
    It usually needs to be run after changing various aspects of the
.br
    configuration. The configuration documentation will mention the exact
.br
    command to use in such case.
.br

.br
    Warning: the 'update' command must not be run in parallel with other update
.br
             commands like 'replication' or 'add\-data'.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-postcodes\fR
Update postcode centroid table

.TP
\fB\-\-word\-counts\fR
Compute frequency of full\-word search terms

.TP
\fB\-\-address\-levels\fR
Reimport address level configuration

.TP
\fB\-\-functions\fR
Update the PL/pgSQL functions in the database

.TP
\fB\-\-wiki\-data\fR
Update Wikipedia/data importance numbers

.TP
\fB\-\-importance\fR
Recompute place importances (expensive!)

.TP
\fB\-\-website\fR
Refresh the directory that serves the scripts for the web API

.TP
\fB\-\-no\-diff\-updates\fR
Do not enable code for propagating updates

.TP
\fB\-\-enable\-debug\-statements\fR
Enable debug warning statements in functions

.SH OPTIONS 'nominatim admin'
usage: nominatim admin [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                       (--warm | --check-database | --migrate | --analyse-indexing)
                       [--search-only] [--reverse-only]
                       [--osm-id OSM_ID | --place-id PLACE_ID]

    Analyse and maintain the database.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-warm\fR
Warm database caches for search and reverse queries

.TP
\fB\-\-check\-database\fR
Check that the database is complete and operational

.TP
\fB\-\-migrate\fR
Migrate the database to a new software version

.TP
\fB\-\-analyse\-indexing\fR
Print performance analysis of the indexing process

.TP
\fB\-\-search\-only\fR
Only pre\-warm tables for search queries

.TP
\fB\-\-reverse\-only\fR
Only pre\-warm tables for reverse queries

.TP
\fB\-\-osm\-id\fR \fI\,OSM_ID\/\fR
Analyse indexing of the given OSM object

.TP
\fB\-\-place\-id\fR \fI\,PLACE_ID\/\fR
Analyse indexing of the given Nominatim object

.SH OPTIONS 'nominatim export'
usage: nominatim export [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                        [--output-type {continent,country,state,county,city,suburb,street,path}]
                        [--output-format OUTPUT_FORMAT]
                        [--output-all-postcodes] [--language LANGUAGE]
                        [--restrict-to-country COUNTRY_CODE]
                        [--restrict-to-osm-node ID] [--restrict-to-osm-way ID]
                        [--restrict-to-osm-relation ID]

    Export addresses as CSV file from the database.
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-output\-type\fR {continent,country,state,county,city,suburb,street,path}
Type of places to output (default: street)

.TP
\fB\-\-output\-format\fR \fI\,OUTPUT_FORMAT\/\fR
Semicolon\-separated list of address types (see \-\-output\-type). Multiple ranks can be merged into one column by simply using a comma\-separated list.

.TP
\fB\-\-output\-all\-postcodes\fR
List all postcodes for address instead of just the most likely one

.TP
\fB\-\-language\fR \fI\,LANGUAGE\/\fR
Preferred language for output (use local name, if omitted)

.TP
\fB\-\-restrict\-to\-country\fR COUNTRY_CODE
Export only objects within country

.TP
\fB\-\-restrict\-to\-osm\-node\fR ID
Export only children of this OSM node

.TP
\fB\-\-restrict\-to\-osm\-way\fR ID
Export only children of this OSM way

.TP
\fB\-\-restrict\-to\-osm\-relation\fR ID
Export only children of this OSM relation

.SH OPTIONS 'nominatim serve'
usage: nominatim serve [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                       [--server SERVER]

    Start a simple web server for serving the API.
.br

.br
    This command starts the built\-in PHP webserver to serve the website
.br
    from the current project directory. This webserver is only suitable
.br
    for testing and development. Do not use it in production setups!
.br

.br
    By the default, the webserver can be accessed at: http://127.0.0.1:8088
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-server\fR \fI\,SERVER\/\fR
The address the server will listen to.

.SH OPTIONS 'nominatim search'
usage: nominatim search [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                        [--query QUERY] [--street STREET] [--city CITY]
                        [--county COUNTY] [--state STATE] [--country COUNTRY]
                        [--postalcode POSTALCODE]
                        [--format {xml,json,jsonv2,geojson,geocodejson}]
                        [--addressdetails] [--extratags] [--namedetails]
                        [--lang LANGS]
                        [--polygon-output {geojson,kml,svg,text}]
                        [--polygon-threshold TOLERANCE] [--countrycodes CC,..]
                        [--exclude_place_ids ID,..] [--limit LIMIT]
                        [--viewbox X1,Y1,X2,Y2] [--bounded] [--no-dedupe]

    Execute a search query.
.br

.br
    This command works exactly the same as if calling the /search endpoint on
.br
    the web API. See the online documentation for more details on the
.br
    various parameters:
.br
    https://nominatim.org/release\-docs/latest/api/Search/
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-query\fR \fI\,QUERY\/\fR
Free\-form query string

.TP
\fB\-\-street\fR \fI\,STREET\/\fR
Structured query: housenumber and street

.TP
\fB\-\-city\fR \fI\,CITY\/\fR
Structured query: city, town or village

.TP
\fB\-\-county\fR \fI\,COUNTY\/\fR
Structured query: county

.TP
\fB\-\-state\fR \fI\,STATE\/\fR
Structured query: state

.TP
\fB\-\-country\fR \fI\,COUNTRY\/\fR
Structured query: country

.TP
\fB\-\-postalcode\fR \fI\,POSTALCODE\/\fR
Structured query: postcode

.TP
\fB\-\-format\fR {xml,json,jsonv2,geojson,geocodejson}
Format of result

.TP
\fB\-\-addressdetails\fR
Include a breakdown of the address into elements

.TP
\fB\-\-extratags\fR
Include additional information if available (e.g. wikipedia link, opening hours)

.TP
\fB\-\-namedetails\fR
Include a list of alternative names

.TP
\fB\-\-lang\fR LANGS, \fB\-\-accept\-language\fR LANGS
Preferred language order for presenting search results

.TP
\fB\-\-polygon\-output\fR {geojson,kml,svg,text}
Output geometry of results as a GeoJSON, KML, SVG or WKT

.TP
\fB\-\-polygon\-threshold\fR TOLERANCE
Simplify output geometry.Parameter is difference tolerance in degrees.

.TP
\fB\-\-countrycodes\fR CC,..
Limit search results to one or more countries

.TP
\fB\-\-exclude_place_ids\fR ID,..
List of search object to be excluded

.TP
\fB\-\-limit\fR \fI\,LIMIT\/\fR
Limit the number of returned results

.TP
\fB\-\-viewbox\fR X1,Y1,X2,Y2
Preferred area to find search results

.TP
\fB\-\-bounded\fR
Strictly restrict results to viewbox area

.TP
\fB\-\-no\-dedupe\fR
Do not remove duplicates from the result list

.SH OPTIONS 'nominatim reverse'
usage: nominatim reverse [-h] [-q] [-v] [--project-dir DIR] [-j NUM] --lat LAT
                         --lon LON [--zoom ZOOM]
                         [--format {xml,json,jsonv2,geojson,geocodejson}]
                         [--addressdetails] [--extratags] [--namedetails]
                         [--lang LANGS]
                         [--polygon-output {geojson,kml,svg,text}]
                         [--polygon-threshold TOLERANCE]

    Execute API reverse query.
.br

.br
    This command works exactly the same as if calling the /reverse endpoint on
.br
    the web API. See the online documentation for more details on the
.br
    various parameters:
.br
    https://nominatim.org/release\-docs/latest/api/Reverse/
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-lat\fR \fI\,LAT\/\fR
Latitude of coordinate to look up (in WGS84)

.TP
\fB\-\-lon\fR \fI\,LON\/\fR
Longitude of coordinate to look up (in WGS84)

.TP
\fB\-\-zoom\fR \fI\,ZOOM\/\fR
Level of detail required for the address

.TP
\fB\-\-format\fR {xml,json,jsonv2,geojson,geocodejson}
Format of result

.TP
\fB\-\-addressdetails\fR
Include a breakdown of the address into elements

.TP
\fB\-\-extratags\fR
Include additional information if available (e.g. wikipedia link, opening hours)

.TP
\fB\-\-namedetails\fR
Include a list of alternative names

.TP
\fB\-\-lang\fR LANGS, \fB\-\-accept\-language\fR LANGS
Preferred language order for presenting search results

.TP
\fB\-\-polygon\-output\fR {geojson,kml,svg,text}
Output geometry of results as a GeoJSON, KML, SVG or WKT

.TP
\fB\-\-polygon\-threshold\fR TOLERANCE
Simplify output geometry.Parameter is difference tolerance in degrees.

.SH OPTIONS 'nominatim lookup'
usage: nominatim lookup [-h] [-q] [-v] [--project-dir DIR] [-j NUM] --id OSMID
                        [--format {xml,json,jsonv2,geojson,geocodejson}]
                        [--addressdetails] [--extratags] [--namedetails]
                        [--lang LANGS]
                        [--polygon-output {geojson,kml,svg,text}]
                        [--polygon-threshold TOLERANCE]

    Execute API lookup query.
.br

.br
    This command works exactly the same as if calling the /lookup endpoint on
.br
    the web API. See the online documentation for more details on the
.br
    various parameters:
.br
    https://nominatim.org/release\-docs/latest/api/Lookup/
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-id\fR OSMID
OSM id to lookup in format <NRW><id> (may be repeated)

.TP
\fB\-\-format\fR {xml,json,jsonv2,geojson,geocodejson}
Format of result

.TP
\fB\-\-addressdetails\fR
Include a breakdown of the address into elements

.TP
\fB\-\-extratags\fR
Include additional information if available (e.g. wikipedia link, opening hours)

.TP
\fB\-\-namedetails\fR
Include a list of alternative names

.TP
\fB\-\-lang\fR LANGS, \fB\-\-accept\-language\fR LANGS
Preferred language order for presenting search results

.TP
\fB\-\-polygon\-output\fR {geojson,kml,svg,text}
Output geometry of results as a GeoJSON, KML, SVG or WKT

.TP
\fB\-\-polygon\-threshold\fR TOLERANCE
Simplify output geometry.Parameter is difference tolerance in degrees.

.SH OPTIONS 'nominatim details'
usage: nominatim details [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                         (--node NODE | --way WAY | --relation RELATION | --place_id PLACE_ID)
                         [--class OBJECT_CLASS] [--addressdetails]
                         [--keywords] [--linkedplaces] [--hierarchy]
                         [--group_hierarchy] [--polygon_geojson]
                         [--lang LANGS]

    Execute API details query.
.br

.br
    This command works exactly the same as if calling the /details endpoint on
.br
    the web API. See the online documentation for more details on the
.br
    various parameters:
.br
    https://nominatim.org/release\-docs/latest/api/Details/
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-node\fR \fI\,NODE\/\fR, \fB\-n\fR \fI\,NODE\/\fR
Look up the OSM node with the given ID.

.TP
\fB\-\-way\fR \fI\,WAY\/\fR, \fB\-w\fR \fI\,WAY\/\fR
Look up the OSM way with the given ID.

.TP
\fB\-\-relation\fR \fI\,RELATION\/\fR, \fB\-r\fR \fI\,RELATION\/\fR
Look up the OSM relation with the given ID.

.TP
\fB\-\-place_id\fR \fI\,PLACE_ID\/\fR, \fB\-p\fR \fI\,PLACE_ID\/\fR
Database internal identifier of the OSM object to look up

.TP
\fB\-\-class\fR \fI\,OBJECT_CLASS\/\fR
Class type to disambiguated multiple entries of the same object.

.TP
\fB\-\-addressdetails\fR
Include a breakdown of the address into elements

.TP
\fB\-\-keywords\fR
Include a list of name keywords and address keywords

.TP
\fB\-\-linkedplaces\fR
Include a details of places that are linked with this one

.TP
\fB\-\-hierarchy\fR
Include details of places lower in the address hierarchy

.TP
\fB\-\-group_hierarchy\fR
Group the places by type

.TP
\fB\-\-polygon_geojson\fR
Include geometry of result

.TP
\fB\-\-lang\fR LANGS, \fB\-\-accept\-language\fR LANGS
Preferred language order for presenting search results

.SH OPTIONS 'nominatim status'
usage: nominatim status [-h] [-q] [-v] [--project-dir DIR] [-j NUM]
                        [--format {text,json}]

    Execute API status query.
.br

.br
    This command works exactly the same as if calling the /status endpoint on
.br
    the web API. See the online documentation for more details on the
.br
    various parameters:
.br
    https://nominatim.org/release\-docs/latest/api/Status/
.br
    



.TP
\fB\-q\fR, \fB\-\-quiet\fR
Print only error messages

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verboseness of output

.TP
\fB\-\-project\-dir\fR DIR
Base directory of the Nominatim installation (default:.)

.TP
\fB\-j\fR NUM, \fB\-\-threads\fR NUM
Number of parallel threads to use

.TP
\fB\-\-format\fR {text,json}
Format of result

.SH AUTHORS
.B Nominatim
was written by the Nominatim developer community <info@nominatim.org>.
.SH DISTRIBUTION
The latest version of Nominatim may be downloaded from
.UR https://nominatim.org
.UE
