#!/bin/sh
#
# Plugin to monitor the age of the imported data in the rendering db
#
# Can be configured through libpq environment variables, for example
# PGUSER, PGDATABASE, etc. See man page of psql for more information
#
# Parameters: 
#
#       config   (required)
#       autoconf (optional - used by munin-config)
#
 
if [ "$1" = "config" ]; then
 
        echo 'graph_title Data import lag' 
        echo 'graph_args --base 1000 -l 0' 
        echo 'graph_vlabel minutes' 
        echo 'graph_category nominatim' 
        echo 'age.label DB import age' 
        echo 'age.type GAUGE' 
        echo 'age.cdef age,60,/'
        exit 0
fi
 

delay=`psql -c "copy (select extract(epoch from timezone('utc', now())-lastimportdate)::int from import_status) to stdout"`
 
 
echo "age.value $delay"
